# Install some bioinformatics software


---
  - name: Check if Kallisto v 0.43.1 is installed in opt/
    stat:
      path: /opt/kallisto_linux-v0.43.1/kallisto
    register: kallisto_result
    failed_when: kallisto_result.stat.exists == false
    ignore_errors: true

  - name: Download and Uncompress Kallisto 0.43.1 tarball
    unarchive:
      src: https://github.com/pachterlab/kallisto/releases/download/v0.43.1/kallisto_linux-v0.43.1.tar.gz
      dest: /opt/
      remote_src: True
    become: true
    when: kallisto_result.stat.exists == false

  - name: Set Kallisto path
    set_fact:
      kallisto_path: /opt/kallisto_linux-v0.43.1/
    when: kallisto_result.stat.exists == false

  - name: Add Kallisto to path
    lineinfile:
      dest: /etc/environment
      state: present
      backrefs: yes
      regexp: 'PATH=(["]*)((?!.*?{{kallisto_path}}).*?)(["]*)$'
      line: 'PATH=\1\2:{{kallisto_path}}\3'
    when: kallisto_result.stat.exists == false

  - name: Check if HiSat2 v 2.1.0 is installed in opt/
    stat:
      path: /opt/hisat2-2.1.0/
    register: hisat_result
    failed_when: hisat_result.stat.exists == false
    ignore_errors: true

  - name: Download and Uncompress HiSat2 v 2.1.0 zipfile
    unarchive:
      src: ftp://ftp.ccb.jhu.edu/pub/infphilo/hisat2/downloads/hisat2-2.1.0-Linux_x86_64.zip
      dest: /opt/
      remote_src: True
    become: true
    when: hisat_result.stat.exists == false

  - name: Set HiSat2 path
    set_fact:
      hisat_path: /opt/hisat2-2.1.0/
    when: hisat_result.stat.exists == false

  - name: Add HiSat2 to path
    lineinfile:
      dest: /etc/environment
      state: present
      backrefs: yes
      regexp: 'PATH=(["]*)((?!.*?{{hisat_path}}).*?)(["]*)$'
      line: 'PATH=\1\2:{{hisat_path}}\3'
    when: hisat_result.stat.exists == false

  - name: Check if stringtie v 1.3.3 is installed in opt/
    stat:
      path: /opt/stringtie-1.3.3b.Linux_x86_64/
    register: stringtie_result
    failed_when: stringtie_result.stat.exists == false
    ignore_errors: true

  - name: Download and Uncompress stringtie v 1.3.3 tarball
    unarchive:
      src: http://ccb.jhu.edu/software/stringtie/dl/stringtie-1.3.3b.Linux_x86_64.tar.gz
      dest: /opt/
      remote_src: True
    become: true
    when: stringtie_result.stat.exists == false

  - name: Set stringtie path
    set_fact:
      stringtie_path: /opt/stringtie-1.3.3b.Linux_x86_64/
    when: stringtie_result.stat.exists == false

  - name: Add stringtie to path
    lineinfile:
      dest: /etc/environment
      state: present
      backrefs: yes
      regexp: 'PATH=(["]*)((?!.*?{{stringtie_path}}).*?)(["]*)$'
      line: 'PATH=\1\2:{{stringtie_path}}\3'
    when: stringtie_result.stat.exists == false
