---

- hosts: Atmosphere # apples to all instances under this name in a hosts file
  remote_user: root # will be working as root
  become: yes # should become the root user (sudo privillaged)
  become_method: sudo
  gather_facts: no
  vars:
    local_ip: 
  pre_tasks:
    - name: stop fail2ban
      service: name=fail2ban state=stopped

    - name: Check if control machine IP is on fail2ban whitelist
      shell: grep {{local_ip}} /etc/fail2ban/jail.local
      register: ip_result
      ignore_errors: true

    - name: edit fail2ban config
      shell: >
        sed '/^ignoreip/s/$/ {{local_ip}}/' /etc/fail2ban/jail.local
        > jail.tmp && mv jail.tmp /etc/fail2ban/jail.local
      when: ip_result|failed

    - name: restartfail2ban
      service: name=fail2ban state=restarted

  roles:
    - role: rstudio-desktop-and-server
    #- role: rstudio-desktop-and-server-w-kallisto-sleuth
    #- role: bioinformatics
    - role: anaconda
    - role: jupyterhub
    - role: data_carpentry_genomics
    - role: dc_bioinformatics
...
