# Install some bioinformatics software


---
  - name: Check if Kallisto v 0.43.1 is installed in opt/
    stat:
      path: /opt/kallisto_linux-v0.43.1/kallisto
    register: kallisto_result
    failed_when: kallisto_result.stat.exists == false
    ignore_errors: true


  - name: Download and Uncompress Kallisto 0.43.1 tarball
    unarchive:
      src: https://github.com/pachterlab/kallisto/releases/download/v0.43.1/kallisto_linux-v0.43.1.tar.gz
      dest: /opt/
      remote_src: True
    become: true
    when: kallisto_result.stat.exists == false

  - name: Set Kallisto path
    set_fact:
      kallisto_path: /opt/kallisto_linux-v0.43.1/

  - name: Add Kallisto to path
    lineinfile:
      dest: /etc/environment
      state: present
      backrefs: yes
      regexp: 'PATH=(["]*)((?!.*?{{kallisto_path}}).*?)(["]*)$'
      line: 'PATH=\1\2:{{kallisto_path}}\3'
    when: kallisto_result.stat.exists == false
